/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import planeaciónagregada.VariaciónTrabajo;

/**
 *
 * @author josej
 */
public class PA extends javax.swing.JFrame {

    /**
     * Creates new form PA
     */
    public PA() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bnIniciar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tP1 = new javax.swing.JTextField();
        tP2 = new javax.swing.JTextField();
        tP3 = new javax.swing.JTextField();
        tP4 = new javax.swing.JTextField();
        tP5 = new javax.swing.JTextField();
        tP6 = new javax.swing.JTextField();
        tPD1 = new javax.swing.JTextField();
        tPD2 = new javax.swing.JTextField();
        tPD3 = new javax.swing.JTextField();
        tPD4 = new javax.swing.JTextField();
        tPD5 = new javax.swing.JTextField();
        tPD6 = new javax.swing.JTextField();
        tPH1 = new javax.swing.JTextField();
        tPH2 = new javax.swing.JTextField();
        tPH3 = new javax.swing.JTextField();
        tPH4 = new javax.swing.JTextField();
        tPH5 = new javax.swing.JTextField();
        tPH6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tP7 = new javax.swing.JTextField();
        tP8 = new javax.swing.JTextField();
        tP9 = new javax.swing.JTextField();
        tP10 = new javax.swing.JTextField();
        tP11 = new javax.swing.JTextField();
        tP12 = new javax.swing.JTextField();
        tPD7 = new javax.swing.JTextField();
        tPD8 = new javax.swing.JTextField();
        tPD9 = new javax.swing.JTextField();
        tPD10 = new javax.swing.JTextField();
        tPD11 = new javax.swing.JTextField();
        tPD12 = new javax.swing.JTextField();
        tPH7 = new javax.swing.JTextField();
        tPH8 = new javax.swing.JTextField();
        tPH9 = new javax.swing.JTextField();
        tPH10 = new javax.swing.JTextField();
        tPH11 = new javax.swing.JTextField();
        tPH12 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tInventarioSeguridad = new javax.swing.JTextField();
        tHoraTrabajo = new javax.swing.JTextField();
        tCostoDespido = new javax.swing.JTextField();
        tCostoEscasez = new javax.swing.JTextField();
        tCostoContratacion = new javax.swing.JTextField();
        tTiempoRegular = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tInventarioInicial = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tMantenimiento = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jResultado = new javax.swing.JLabel();
        jResultado2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduzca pronósticos, dias y horas (máximo 12)");

        bnIniciar.setText("Iniciar");
        bnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnIniciarActionPerformed(evt);
            }
        });

        jLabel2.setText("1");

        jLabel3.setText("2");

        jLabel4.setText("3");

        jLabel5.setText("4");

        jLabel6.setText("5");

        jLabel7.setText("6");

        jLabel8.setText("Pronóstico");

        jLabel9.setText("Días");

        jLabel10.setText("Horas");

        tP1.setText("0");
        tP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tP1ActionPerformed(evt);
            }
        });

        tP2.setText("0");

        tP3.setText("0");

        tP4.setText("0");

        tP5.setText("0");

        tP6.setText("0");

        tPD1.setText("0");
        tPD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPD1ActionPerformed(evt);
            }
        });

        tPD2.setText("0");
        tPD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPD2ActionPerformed(evt);
            }
        });

        tPD3.setText("0");
        tPD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPD3ActionPerformed(evt);
            }
        });

        tPD4.setText("0");

        tPD5.setText("0");

        tPD6.setText("0");

        tPH1.setText("0");
        tPH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPH1ActionPerformed(evt);
            }
        });

        tPH2.setText("0");
        tPH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPH2ActionPerformed(evt);
            }
        });

        tPH3.setText("0");

        tPH4.setText("0");
        tPH4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPH4ActionPerformed(evt);
            }
        });

        tPH5.setText("0");
        tPH5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPH5ActionPerformed(evt);
            }
        });

        tPH6.setText("0");

        jLabel11.setText("Pronóstico");

        jLabel12.setText("Dias");

        jLabel13.setText("Horas");

        jLabel14.setText("7");

        jLabel15.setText("8");

        jLabel16.setText("9");

        jLabel17.setText("10");

        jLabel18.setText("11");

        jLabel19.setText("12");

        tP7.setText("0");
        tP7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tP7ActionPerformed(evt);
            }
        });

        tP8.setText("0");
        tP8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tP8ActionPerformed(evt);
            }
        });

        tP9.setText("0");

        tP10.setText("0");
        tP10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tP10ActionPerformed(evt);
            }
        });

        tP11.setText("0");

        tP12.setText("0");

        tPD7.setText("0");

        tPD8.setText("0");
        tPD8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPD8ActionPerformed(evt);
            }
        });

        tPD9.setText("0");
        tPD9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPD9ActionPerformed(evt);
            }
        });

        tPD10.setText("0");
        tPD10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPD10ActionPerformed(evt);
            }
        });

        tPD11.setText("0");

        tPD12.setText("0");
        tPD12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPD12ActionPerformed(evt);
            }
        });

        tPH7.setText("0");
        tPH7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPH7ActionPerformed(evt);
            }
        });

        tPH8.setText("0");
        tPH8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPH8ActionPerformed(evt);
            }
        });

        tPH9.setText("0");
        tPH9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPH9ActionPerformed(evt);
            }
        });

        tPH10.setText("0");
        tPH10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPH10ActionPerformed(evt);
            }
        });

        tPH11.setText("0");

        tPH12.setText("0");

        jLabel20.setText("Introducir valores iniciales");

        jLabel21.setText("Inventario de seguridad");

        jLabel22.setText("Hora de trabajo");

        jLabel23.setText("Costo de contratación");

        jLabel24.setText("Costo de despido");

        jLabel25.setText("Tiempo regular");

        jLabel26.setText("Costo escasez");

        tCostoEscasez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCostoEscasezActionPerformed(evt);
            }
        });

        tTiempoRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTiempoRegularActionPerformed(evt);
            }
        });

        jLabel27.setText("Inventario inicial");

        tInventarioInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tInventarioInicialActionPerformed(evt);
            }
        });

        jLabel28.setText("Mantenimiento");

        tMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMantenimientoActionPerformed(evt);
            }
        });

        jLabel29.setText("Variación de trabajo");

        jLabel30.setText("Trabajo constante");

        jResultado.setText("Total");

        jResultado2.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)
                                .addComponent(jLabel24))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tP3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tP4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tP5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tP6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                            .addComponent(tP2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(tP1)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel10)
                                        .addGap(0, 62, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tPD6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tPD5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tPD4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tPD3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tPD2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tPD1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tPH2)
                                            .addComponent(tPH1)
                                            .addComponent(tPH3)
                                            .addComponent(tPH4)
                                            .addComponent(tPH5)
                                            .addComponent(tPH6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel19))
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(230, 230, 230))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tCostoContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tCostoEscasez, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tTiempoRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel27)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(199, 199, 199))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(161, 161, 161)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tP12, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tP11, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tP10, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tP9, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tP8, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tP7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)))
                                    .addGap(23, 23, 23)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tPD12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                            .addComponent(tPD11, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tPD10, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tPD9, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tPD8, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tPD7, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(jLabel12))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tPH8)
                                            .addComponent(tPH9)
                                            .addComponent(tPH10)
                                            .addComponent(tPH11)
                                            .addComponent(tPH12, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(tPH7))
                                        .addComponent(jLabel13)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tInventarioSeguridad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tHoraTrabajo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tCostoDespido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tInventarioInicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel26)
                                        .addComponent(jLabel28))))
                            .addGap(43, 43, 43)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bnIniciar)
                        .addGap(251, 251, 251))))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jResultado2)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tPD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPD7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPH7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tPD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tP8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPD8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPH8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tPD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tP9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPD9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPH9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tPD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPH4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tP10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPD10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPH10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tPD5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPH5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tP11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPD11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPH11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tPD6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPH6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tP12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPD12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPH12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel19)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addComponent(jLabel20)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel26)
                    .addComponent(tInventarioSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCostoEscasez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(tHoraTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCostoContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(tCostoDespido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTiempoRegular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tInventarioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(tMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(bnIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jResultado)
                    .addComponent(jResultado2))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnIniciarActionPerformed
        int P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12;
    int PD1, PD2, PD3, PD4, PD5, PD6, PD7, PD8, PD9, PD10, PD11, PD12;
    int PH1, PH2, PH3, PH4, PH5, PH6, PH7, PH8, PH9, PH10, PH11, PH12;
    int InventarioInicial, InventarioSeguridad, HoraTrabajo, costoContratacion, CostoDespido, TiempoRegular;
    int CostoEscasez, Mantenimiento;
    P1= Integer.parseInt(tP1.getText());
    P2= Integer.parseInt(tP2.getText());
    P3= Integer.parseInt(tP3.getText());
    P4= Integer.parseInt(tP4.getText());
    P5= Integer.parseInt(tP5.getText());
    P6= Integer.parseInt(tP6.getText());
    P7= Integer.parseInt(tP7.getText());
    P8= Integer.parseInt(tP8.getText());
    P9= Integer.parseInt(tP9.getText());
    P10= Integer.parseInt(tP10.getText());
    P11= Integer.parseInt(tP11.getText());
    P12= Integer.parseInt(tP12.getText());
    PD1= Integer.parseInt(tPD1.getText());
    PD2= Integer.parseInt(tPD2.getText());
    PD3= Integer.parseInt(tPD3.getText());
    PD4= Integer.parseInt(tPD4.getText());
    PD5= Integer.parseInt(tPD5.getText());
    PD6= Integer.parseInt(tPD6.getText());
    PD7= Integer.parseInt(tPD7.getText());
    PD8= Integer.parseInt(tPD8.getText());
    PD9= Integer.parseInt(tPD9.getText());
    PD10= Integer.parseInt(tPD10.getText());
    PD11= Integer.parseInt(tPD11.getText());
    PD12= Integer.parseInt(tPD12.getText());
    PH1= Integer.parseInt(tPH1.getText());
    PH2= Integer.parseInt(tPH2.getText());
    PH3= Integer.parseInt(tPH3.getText());
    PH4= Integer.parseInt(tPH4.getText());
    PH5= Integer.parseInt(tPH5.getText());
    PH6= Integer.parseInt(tPH6.getText());
    PH7= Integer.parseInt(tPH7.getText());
    PH8= Integer.parseInt(tPH8.getText());
    PH9= Integer.parseInt(tPH9.getText());
    PH10= Integer.parseInt(tPH10.getText());
    PH11= Integer.parseInt(tPH11.getText());
    PH12= Integer.parseInt(tPH12.getText());
    InventarioInicial= Integer.parseInt(tInventarioInicial.getText());
    InventarioSeguridad= Integer.parseInt(tInventarioSeguridad.getText());
    HoraTrabajo= Integer.parseInt(tHoraTrabajo.getText());
    costoContratacion= Integer.parseInt(tCostoContratacion.getText());
    CostoDespido= Integer.parseInt(tCostoDespido.getText());
    TiempoRegular= Integer.parseInt(tTiempoRegular.getText());
    
   VariaciónTrabajo s=new VariaciónTrabajo(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, PD1, PD2, PD3, PD4, PD5, PD6, PD7, PD8, PD9, PD10, PD11, PD12,PH1, PH2, PH3, PH4, PH5, PH6, PH7, PH8, PH9, PH10, PH11, PH12, InventarioInicial, InventarioSeguridad, HoraTrabajo, costoContratacion, CostoDespido, TiempoRegular );
   jResultado.setText(String.valueOf(s.OperaVT()));
    
    
    
    }//GEN-LAST:event_bnIniciarActionPerformed

    private void tPH7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPH7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPH7ActionPerformed

    private void tPD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPD2ActionPerformed

    private void tPH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPH5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPH5ActionPerformed

    private void tPD9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPD9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPD9ActionPerformed

    private void tPD10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPD10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPD10ActionPerformed

    private void tPH9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPH9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPH9ActionPerformed

    private void tCostoEscasezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCostoEscasezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCostoEscasezActionPerformed

    private void tTiempoRegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTiempoRegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTiempoRegularActionPerformed

    private void tInventarioInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tInventarioInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tInventarioInicialActionPerformed

    private void tPD12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPD12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPD12ActionPerformed

    private void tP10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tP10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tP10ActionPerformed

    private void tPH10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPH10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPH10ActionPerformed

    private void tP8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tP8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tP8ActionPerformed

    private void tPD8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPD8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPD8ActionPerformed

    private void tPH8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPH8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPH8ActionPerformed

    private void tP7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tP7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tP7ActionPerformed

    private void tPH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPH4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPH4ActionPerformed

    private void tPD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPD3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPD3ActionPerformed

    private void tPH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPH2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPH2ActionPerformed

    private void tPH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPH1ActionPerformed

    private void tPD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPD1ActionPerformed

    private void tP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tP1ActionPerformed

    private void tMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMantenimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jResultado;
    private javax.swing.JLabel jResultado2;
    private javax.swing.JTextField tCostoContratacion;
    private javax.swing.JTextField tCostoDespido;
    private javax.swing.JTextField tCostoEscasez;
    private javax.swing.JTextField tHoraTrabajo;
    private javax.swing.JTextField tInventarioInicial;
    private javax.swing.JTextField tInventarioSeguridad;
    private javax.swing.JTextField tMantenimiento;
    private javax.swing.JTextField tP1;
    private javax.swing.JTextField tP10;
    private javax.swing.JTextField tP11;
    private javax.swing.JTextField tP12;
    private javax.swing.JTextField tP2;
    private javax.swing.JTextField tP3;
    private javax.swing.JTextField tP4;
    private javax.swing.JTextField tP5;
    private javax.swing.JTextField tP6;
    private javax.swing.JTextField tP7;
    private javax.swing.JTextField tP8;
    private javax.swing.JTextField tP9;
    private javax.swing.JTextField tPD1;
    private javax.swing.JTextField tPD10;
    private javax.swing.JTextField tPD11;
    private javax.swing.JTextField tPD12;
    private javax.swing.JTextField tPD2;
    private javax.swing.JTextField tPD3;
    private javax.swing.JTextField tPD4;
    private javax.swing.JTextField tPD5;
    private javax.swing.JTextField tPD6;
    private javax.swing.JTextField tPD7;
    private javax.swing.JTextField tPD8;
    private javax.swing.JTextField tPD9;
    private javax.swing.JTextField tPH1;
    private javax.swing.JTextField tPH10;
    private javax.swing.JTextField tPH11;
    private javax.swing.JTextField tPH12;
    private javax.swing.JTextField tPH2;
    private javax.swing.JTextField tPH3;
    private javax.swing.JTextField tPH4;
    private javax.swing.JTextField tPH5;
    private javax.swing.JTextField tPH6;
    private javax.swing.JTextField tPH7;
    private javax.swing.JTextField tPH8;
    private javax.swing.JTextField tPH9;
    private javax.swing.JTextField tTiempoRegular;
    // End of variables declaration//GEN-END:variables
}
